### ISSUE TITLE
sponge .... no work

### ISSUE THREAD

**Issue by Bucky420** [DoctorFTB/StoneBlock-Dimensions#3]
Caused by: java.lang.ClassCastException: ftblag.stoneblockdimensions.SBUTeleporter cannot be cast to org.spongepowered.api.world.PortalAgent
        at org.spongepowered.common.SpongeImplHooks.registerPortalAgentType(SpongeImplHooks.java:1412) ~[SpongeImplHooks.class:1.12.2-2768-7.1.5-RC3514]
        at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:351) ~[EntityUtil.class:1.12.2-2768-7.1.5-RC3514]
        at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:222) ~[EntityUtil.class:1.12.2-2768-7.1.5-RC3514]
        at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:5563) ~[oq.class:?]
        at ftblag.stoneblockdimensions.SBUEvents.teleport(SBUEvents.java:70) ~[SBUEvents.class:?]
        at ftblag.stoneblockdimensions.SBUEvents.move(SBUEvents.java:39) ~[SBUEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_601_SBUEvents_move_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more

**Comment by modmuss50** [comment]
There seems to be an open issue on sponge's tracker about this, https://github.com/SpongePowered/SpongeForge/issues/2266

**Comment by Bucky420** [comment]
yes can u use the old way thoe ... for tping people it should still work

**Comment by modmuss50** [comment]
It used to use the old way for teleportation, but it had some issues, so I changed it to use the new teleportation api in forge.

Using old, broken API's to support sponge wont happen, FTB usually doesnt support anything sponge but this is a special case as its required for pack progression. There is nothing that can be done easily on the mods end to fix this, so a fix from sponge is required. (Please correct me if im worng)

**Comment by nzminecraftDOTcom** [comment]
Guess the only option then, is to remove the mod from the server, or let people continue to crash. Kinda sad.

**Comment by Bucky420** [comment]
call sponge code then and compile for a sponge version seams easy enough i got a modder i will get on this :)

**Comment by modmuss50** [comment]
This mod is required for stone block 2 to function correctly, removing itsnt really an option if you want to be able to play the pack.



> call sponge code then and compile for a sponge version seams easy enough i got a modder i will get on this :)

Can that modder not fix the issue, or help suggest a fix here? I know nothing about sponge, and am willing to help fix the issue, where possible. Rewriting the teleporting code to use the old buggy system is not an option though. A lot of mods will be using this/start to be using this for their teleportation so fixing the issue in sponge might not be a bad idea.

**Comment by nzminecraftDOTcom** [comment]
Do you know the dimension ID's for the mining dimension etc?
Using COFH I can workaround using the TPX command.

**Comment by modmuss50** [comment]
Fixed, update sponge

**Comment by nzminecraftDOTcom** [comment]
Legend!

**Comment by DMCK96** [comment]
This error is still occurring on SpongeForge 2768-7.1.4 and Stoneblock2 1.4 (Stoneblock Dimensions 1.0.2)
